load("@bazel_tools//tools/build_defs/repo:git.bzl", "local_repository")

local_repository(
    name = "toolchains_cross_cc",
    path = "../..",
)

load("@toolchains_cross_cc//toolchain:toolchain.bzl", "cross_cc_toolchain")

cross_cc_toolchain(
    name = "aarch64_linux_gnu_gcc",
    compiler = "gcc",
    target = "aarch64-linux-gnu",
    libc = "glibc",
)

register_toolchains("//:aarch64_linux_gnu_gcc")
